### ISSUE TITLE
Management - follow up on previous deviation from 2019

### ISSUE THREAD

**Issue by AnnaLeinfelt** [Clinical-Genomics/cgp-preparation-for-swedac-audit-2020#19]
All have been approved but some will be discussed (marked).

- [x] ACL_01 | Ledningssystem | I rutinen för klagomål är det inte angivet att det ska hanteras av en personal som inte varit involverad i ursprungliga laboratorieaktiviteten.

 **Åtgärden godkänd men kommer följas upp.** 
- [ ] Om tid finns, gör om EA avvikelse flödet och förtydliga detta.  Assign to **(AL)**

- [ ] ACL_02 | Ledningssystem | Laboratoriets rutin är bristfällig avseende för att säkerställa att åtgärder (inklusive att vid behov avbryta eller upprepa arbete, eller att hålla inne med rapporter) grundar sig på de risknivåer som har fastställts av laboratoriet. Exempel visar när prov enligt metodbeskrivning inte skulle godkänts, har ändå godkänts efter kommentar och gått vidare till nästa steg i analysen. Där har provet blivit godkänt.

- Automated WGS prepp on BRAVO och qPCR analys inskickat som exempel på att det finns toleransnivåer för QC stegen.
 **Åtgärden godkänd men kommer följas upp.** 
assign to: **ALY**

- [x] ACL_03 | Ledningssystem | När en avvikelse inträffar ska laboratoriet utvärdera behovet av åtgärder för att eliminera orsaken eller orsakerna till avvikelsen så att den inte upprepas eller förekommer någon annanstans genom att bland annat fastställa orsakerna till avvikelsen. Laboratoriets orsaksanalys vid avvikelsehantering är bristfälliga eller förekommer inte på flertalet avvikelser.

Assign to: **AL**

- [ ] ACL_04 | Ledningssystem | Agendan för ledningens genomgång är inte uppdaterad enligt krav i 17025:2017.Vid tidigare protokoll av ledningens genomgång saknas status på åtgärder från tidigare utförda ledningsgenomgångar, samt vilka resurser som är utsedda att för att verkställa beslut och åtgärder som beslutats. Rutinen för ledningens genomgång är inte uppdaterad i kvalitetsmanualen.

Last performed management review (Jan 2020) to be discussed.
Prepare by reading protocol.
Assign to: **AL, VW**

- [x] ACL_05 | Ledningssystem | Laboratoriet ska beakta de risker och möjligheter som är förknippade med laboratorieaktiviteter såsom införande av en ny metod. Laboratoriet ska planera för hantering av dessa risker och möjligheter, t ex värdera om en ny metod bör ackrediteras, om det är en utökning av ackreditering eller om metoden bör sättas upp på lista för flexibel ackreditering och metodlistan. Laboratoriet ska planera för och hur de ska integrera och implementera dessa åtgärder.

Will be discussed 
Assign to: **AL, VW**

- [x] ACL_06 | Ledningssystem | List of changes of Activities Conducted (under the flexible accreditation) 1821:5 stämmer inte överens med lista Method list 1113:19.

Will be discussed at audit 10/6.
Assign to: **AL**

- [x] Assign the people that are involved in the task

**Comment by vwirta** [comment]
> * [ ]  ACL_05 | Ledningssystem | Laboratoriet ska beakta de risker och möjligheter som är förknippade med laboratorieaktiviteter såsom införande av en ny metod. Laboratoriet ska planera för hantering av dessa risker och möjligheter, t ex värdera om en ny metod bör ackrediteras, om det är en utökning av ackreditering eller om metoden bör sättas upp på lista för flexibel ackreditering och metodlistan. Laboratoriet ska planera för och hur de ska integrera och implementera dessa åtgärder.
> 
> Will be discussed
> Assign to: **AL, VW**

@AnnaLeinfelt angående detta, vad tror du om följande?

Vi lägger till ett stycke i 1007 under 2.7.1

Clinical Genomics Stockholm operates both accredited and non-accredited services. For each new service established, it should be considered if this service is to be accredited or not. 
A reminder to consider is available in the Implementation plan template (1187).  

Behöver vi eg skriva mer än detta?

**Comment by AnnaLeinfelt** [comment]
> > * [ ]   ACL_05 | Ledningssystem | Laboratoriet ska beakta de risker och möjligheter som är förknippade med laboratorieaktiviteter såsom införande av en ny metod. Laboratoriet ska planera för hantering av dessa risker och möjligheter, t ex värdera om en ny metod bör ackrediteras, om det är en utökning av ackreditering eller om metoden bör sättas upp på lista för flexibel ackreditering och metodlistan. Laboratoriet ska planera för och hur de ska integrera och implementera dessa åtgärder.
> > 
> > Will be discussed
> > Assign to: **AL, VW**
> 
> @AnnaLeinfelt angående detta, vad tror du om följande?
> 
> Vi lägger till ett stycke i 1007 under 2.7.1
> 
> Clinical Genomics Stockholm operates both accredited and non-accredited services. For each new service established, it should be considered if this service is to be accredited or not.
> A reminder to consider is available in the Implementation plan template (1187).
> 
> Behöver vi eg skriva mer än detta?

@vwirta Det blir toppen. Och finns med i templatet av 1187 sedan förra året.
