### ISSUE TITLE
IT - follow up on previous deviation from 2019

### ISSUE THREAD

**Issue by AnnaLeinfelt** [Clinical-Genomics/cgp-preparation-for-swedac-audit-2020#21]
All IT from 2019 listed below. All have been approved but some will be discussed (marked).

- [x] LC_01 | IT | Verifiering av föregående IT-bedömning avvikelse BO_02 visar att listan av leverantörer inte är fullständig och behöver uppdateras. De leverantörer som tillkommit behöver också utvärderas.

Supplier assessments needs to be performed

- [x] Assign to **AZ, AL, PG**
[Suppliers to assess](https://docs.google.com/spreadsheets/d/1qGobfEza9ukrW8qKXUnKmye8Oj1vq0chs3sxWgOUnO0/edit#gid=799206903)

LC_02 | IT | Verifiering av föregående IT-bedömning avvikelse BO_07 visar att dokumentet "Generell LIMS dokumentation" tappat spårbarhet till Clarity LIMS versionsnummer vid flytt till GitHub.

- [ ] LC_03 | IT | Det saknas en riskanlys inför pilotinförandet av GitHub som repository för laboratoriets källkod med avseende på  informationssäkerhetsaspekterna Tillgänglighet, Riktighet och Konfidentialitet.

To be discussed.
Assign to **PG**

LC_04 | IT | En beslutade och dokumenterad metod för riskanalys kunde inte uppvisas vid bedömningstillfället.

- [x] LC_05 | IT | Laboratoriet kunde inte uppvisa en Disaster och Recoveryplan (Kontinuitetsplan) för IT-systemen vid bedömningstillfället.

[Disaster and recovery plan  2020-05-28](https://docs.google.com/spreadsheets/d/1BSOWHC_K1UHS9j1PwJa9Us9sV-BkG3FclvH-YVvVuoM/edit#gid=0)

2019-06-17 av Clinical Genomics, SciLifeLab
En kontinuitetsplan för LIMS ska vara beslutad senast 2019-09-30.

This will be followed up.

- [ ] Assign **VW, PG**

- [x] LC_06 | IT | Laboratoriet utvecklar och underhåller ca 23 programvaror. Kravställningen på dess funktionalitet kommer främst från laboratoriets interna verksamhet men även externt från kunder. En gemensam eller individuell utvecklingsmodell för programvaror kunde inte uppvisas vid bedömningstillfället. SWEDAC rekommenderar en gemensam utvecklingsmodell.

To be discussed

- [x] Assign to **VW, PG, HS**

- [x] LC_07 | IT | En riskanalys som beaktar antagonistiska hot kunde inte uppvisas vid bedömingstillfället

From swedac: Orsaksanalysen bedöms som fullgod. Vid nästa IT-bedömning bör en riskanalys över antagonistiska hot uppvisas.

Done here: [Disaster and recovery plan  2020-05-28](https://docs.google.com/spreadsheets/d/1BSOWHC_K1UHS9j1PwJa9Us9sV-BkG3FclvH-YVvVuoM/edit#gid=0)

To be discussed

- [ ] Assign to **PG, VW**

- [x] Assign the people that are involved in the task

**Comment by AnnaZetterlund** [comment]
Supplier assessment for lab is done or left with other members of the labteam to finish some off. 
There are some IT related supplier to look at and I leave that for you @patrikgrenfeldt

**Comment by henrikstranneheim** [comment]
**LC_06 | IT | Laboratoriet utvecklar och underhåller ca 23 programvaror. Kravställningen på dess funktionalitet kommer främst från laboratoriets interna verksamhet men även externt från kunder. En gemensam eller individuell utvecklingsmodell för programvaror kunde inte uppvisas vid bedömningstillfället. SWEDAC rekommenderar en gemensam utvecklingsmodell.**

Is it not enough to refer to the development guide and 1042 and 1098: 
`- We have implemented mandatory and recommended guidelines on how to develop software at clinical genomics here: https://github.com/Clinical-Genomics/development and in AM docs 1042 and 1098`

**Comment by vwirta** [comment]
> **LC_06 | IT | Laboratoriet utvecklar och underhåller ca 23 programvaror. Kravställningen på dess funktionalitet kommer främst från laboratoriets interna verksamhet men även externt från kunder. En gemensam eller individuell utvecklingsmodell för programvaror kunde inte uppvisas vid bedömningstillfället. SWEDAC rekommenderar en gemensam utvecklingsmodell.**
> 
> Is it not enough to refer to the development guide and 1042 and 1098:
> `- We have implemented mandatory and recommended guidelines on how to develop software at clinical genomics here: https://github.com/Clinical-Genomics/development and in AM docs 1042 and 1098`

I would say it is enough. The github description is clear and I do think we need to follow swedacs recommendation if we find another solution to be better for us

**Comment by patrikgrenfeldt** [comment]
@AnnaLeinfelt, vad gäller angående LC_04, den har ingen checkbox och inga assignees och ingen kommentar om varför den står där. Saknas det något eller ska den inte vara med?

**Comment by AnnaLeinfelt** [comment]
> @AnnaLeinfelt, vad gäller angående LC_04, den har ingen checkbox och inga assignees och ingen kommentar om varför den står där. Saknas det något eller ska den inte vara med?

Jag tog med alla avvikelser men satte bara rutor för de som ska följas upp.  Så den har ingen action.

**Comment by AnnaLeinfelt** [comment]
> https://github.com/Clinical-Genomics/development

@henrikstranneheim Is this link included in any AM document? Are these recommended guidelines? How are they introduced to staff at Clinical Genomics?

**Comment by patrikgrenfeldt** [comment]
These are recommended guidelines yes. We have it as part of the introduction to new employees where it is relevant
